### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by 3lm0n0** [JuaMateu/grupo_3_vivero#1]
El home deberia estar mas avanzado.

**Comment by JuaMateu** [comment]
No se si vieron la segundaRama que esta mas avanzada.
Igualmente vamos a intentar de juntar todas las ramas

**Comment by JuaMateu** [comment]
Terminada la clase del miercoles nos reunimos y actualizamos el HOME entre todos.
Aun faltan detalles pero esta mas avanzado

**Comment by 3lm0n0** [comment]
Genial, dejaron la rama main y esta actualizada!
