### ISSUE TITLE
Retro

### ISSUE THREAD

**Issue by 3lm0n0** [JuaMateu/grupo_3_vivero#2]
no veo que hayan subido la retro del primer sprint

**Comment by JuaMateu** [comment]
Hicimos una retrospectiva. nos ayudamos de un tablero de Trello con 5 secciones segun el metodo Starfish.
Lo pasamos a un archivo retro.md y dejamos el link del tablero.

Tambien agregamos al readme.md el link al tablero Kanban con las tareas de cada Sprint 
(en caso de que no tengan permisos para ver por favor avisennos)
